import CC from "../assets/CC.jpg";
import DM from "../assets/DM.jpg";
import GD from "../assets/GD.jpg";

export const newsData = [
  {
    title:
      "AI platform for PotentialMetrics to improve cancer prognastic accuracy.",
    time: "08 Mar 2024 ..Uncategorized",
    image: GD,
    introduction:
      "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. But what exactly is minimalism, and how can it benefit you? In this blog post, we’ll explore the principles of minimalism, its advantages, and practical tips to start your minimalist journey.",
    news: "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. Minimalism is a lifestyle choice that encourages individuals to remove excess from their lives, focusing on what truly matters. It’s about living with intention, owning fewer possessions, and creating more space for meaningful experiences and relationships. Minimalism isn’t just about decluttering your home; it’s a holistic approach to life that can lead to greater clarity and contentment. The benefits of minimalism are numerous. It can reduce stress by simplifying your environment, leading to less anxiety. Financially, it encourages mindful spending, helping you save and invest in what truly brings joy and value to your life. With fewer distractions, you can concentrate better on your goals and passions, enhancing productivity and creativity. Additionally, minimalism promotes sustainability and mindful consumption, reducing your ecological footprint. By prioritizing experiences and connections over material possessions, you cultivate deeper, more meaningful relationships with others. To start your minimalist journey, begin by understanding why you want to embrace minimalism. Declutter your space, adopt a one-in, one-out policy for new items, practice mindful consumption, simplify your schedule, and embrace digital minimalism. Minimalism is a journey towards a more intentional, fulfilling life, where letting go of excess allows you to create a space for joy, peace, and meaningful experiences. Start small, be patient with yourself, and remember that minimalism is a personal journey. Embrace the freedom that comes with living a simplified life, and discover the profound impact it can have on your overall well-being.",
  },
  {
    title: "AI platform for .",
    time: "08 Mar 2024 ..Uncategorized",
    image: CC,
    introduction:
      "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. But what exactly is minimalism, and how can it benefit you? In this blog post, we’ll explore the principles of minimalism, its advantages, and practical tips to start your minimalist journey.",
    news: "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. Minimalism is a lifestyle choice that encourages individuals to remove excess from their lives, focusing on what truly matters. It’s about living with intention, owning fewer possessions, and creating more space for meaningful experiences and relationships. Minimalism isn’t just about decluttering your home; it’s a holistic approach to life that can lead to greater clarity and contentment. The benefits of minimalism are numerous. It can reduce stress by simplifying your environment, leading to less anxiety. Financially, it encourages mindful spending, helping you save and invest in what truly brings joy and value to your life. With fewer distractions, you can concentrate better on your goals and passions, enhancing productivity and creativity. Additionally, minimalism promotes sustainability and mindful consumption, reducing your ecological footprint. By prioritizing experiences and connections over material possessions, you cultivate deeper, more meaningful relationships with others. To start your minimalist journey, begin by understanding why you want to embrace minimalism. Declutter your space, adopt a one-in, one-out policy for new items, practice mindful consumption, simplify your schedule, and embrace digital minimalism. Minimalism is a journey towards a more intentional, fulfilling life, where letting go of excess allows you to create a space for joy, peace, and meaningful experiences. Start small, be patient with yourself, and remember that minimalism is a personal journey. Embrace the freedom that comes with living a simplified life, and discover the profound impact it can have on your overall well-being.",
  },
  {
    title: "AI platform for PotentialMetrics to improve.",
    time: "08 Mar 2024 ..Uncategorized",
    image: DM,
    introduction:
      "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. But what exactly is minimalism, and how can it benefit you? In this blog post, we’ll explore the principles of minimalism, its advantages, and practical tips to start your minimalist journey.",
    news: "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. Minimalism is a lifestyle choice that encourages individuals to remove excess from their lives, focusing on what truly matters. It’s about living with intention, owning fewer possessions, and creating more space for meaningful experiences and relationships. Minimalism isn’t just about decluttering your home; it’s a holistic approach to life that can lead to greater clarity and contentment. The benefits of minimalism are numerous. It can reduce stress by simplifying your environment, leading to less anxiety. Financially, it encourages mindful spending, helping you save and invest in what truly brings joy and value to your life. With fewer distractions, you can concentrate better on your goals and passions, enhancing productivity and creativity. Additionally, minimalism promotes sustainability and mindful consumption, reducing your ecological footprint. By prioritizing experiences and connections over material possessions, you cultivate deeper, more meaningful relationships with others. To start your minimalist journey, begin by understanding why you want to embrace minimalism. Declutter your space, adopt a one-in, one-out policy for new items, practice mindful consumption, simplify your schedule, and embrace digital minimalism. Minimalism is a journey towards a more intentional, fulfilling life, where letting go of excess allows you to create a space for joy, peace, and meaningful experiences. Start small, be patient with yourself, and remember that minimalism is a personal journey. Embrace the freedom that comes with living a simplified life, and discover the profound impact it can have on your overall well-being.",
  },
  {
    title: "AI platform for PotentialMetrics to improve.",
    time: "08 Mar 2024 ..Uncategorized",
    image: CC,
    introduction:
      "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. But what exactly is minimalism, and how can it benefit you? In this blog post, we’ll explore the principles of minimalism, its advantages, and practical tips to start your minimalist journey.",
    news: "In a world where consumerism and materialism often dictate our lives, many people are turning to minimalism as a way to reclaim their peace and focus. Minimalism is a lifestyle choice that encourages individuals to remove excess from their lives, focusing on what truly matters. It’s about living with intention, owning fewer possessions, and creating more space for meaningful experiences and relationships. Minimalism isn’t just about decluttering your home; it’s a holistic approach to life that can lead to greater clarity and contentment. The benefits of minimalism are numerous. It can reduce stress by simplifying your environment, leading to less anxiety. Financially, it encourages mindful spending, helping you save and invest in what truly brings joy and value to your life. With fewer distractions, you can concentrate better on your goals and passions, enhancing productivity and creativity. Additionally, minimalism promotes sustainability and mindful consumption, reducing your ecological footprint. By prioritizing experiences and connections over material possessions, you cultivate deeper, more meaningful relationships with others. To start your minimalist journey, begin by understanding why you want to embrace minimalism. Declutter your space, adopt a one-in, one-out policy for new items, practice mindful consumption, simplify your schedule, and embrace digital minimalism. Minimalism is a journey towards a more intentional, fulfilling life, where letting go of excess allows you to create a space for joy, peace, and meaningful experiences. Start small, be patient with yourself, and remember that minimalism is a personal journey. Embrace the freedom that comes with living a simplified life, and discover the profound impact it can have on your overall well-being.",
  },
];
